// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADNpaYdRPCMKz75Ut7gGV37VLg-AwcRo',
    appId: '1:873020037397:web:54a12ffef1eeea3860311c',
    messagingSenderId: '873020037397',
    projectId: 'huskies-app-dev',
    authDomain: 'huskies-app-dev.firebaseapp.com',
    storageBucket: 'huskies-app-dev.appspot.com',
    measurementId: 'G-XVGQQ6J771',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2t8xII8RPQNwHPt3P9OMTszxcKQ-UTA8',
    appId: '1:873020037397:android:315a1bbcfe6a6bb160311c',
    messagingSenderId: '873020037397',
    projectId: 'huskies-app-dev',
    storageBucket: 'huskies-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0_fputT4x_pNAFM4J8oR0f4lgmYgMv8',
    appId: '1:873020037397:ios:933109b8c53dad6860311c',
    messagingSenderId: '873020037397',
    projectId: 'huskies-app-dev',
    storageBucket: 'huskies-app-dev.appspot.com',
    iosBundleId: 'com.example.huskiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0_fputT4x_pNAFM4J8oR0f4lgmYgMv8',
    appId: '1:873020037397:ios:6a40f0c4d12ba4cf60311c',
    messagingSenderId: '873020037397',
    projectId: 'huskies-app-dev',
    storageBucket: 'huskies-app-dev.appspot.com',
    iosBundleId: 'com.example.huskiesApp.RunnerTests',
  );
}
